# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: 0BSD

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/fsfe/reuse-tool
    rev: v2.1.0
    hooks:
    - id: reuse
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies:
          - toml
