# SPDX-FileCopyrightText: 2022 Diego Elio Pettenò
#
# SPDX-License-Identifier: MIT

import logging

import dateparser

from ..lib import pdf_document
from ..lib.renamer import NameComponents, pdfrenamer
from ..lib.utils import extract_account_holder_from_address

_LOGGER = logging.getLogger(__name__)


@pdfrenamer
def invoice(document: pdf_document.Document) -> NameComponents | None:
    logger = _LOGGER.getChild("xero.invoice")

    if document.producer != b"Aspose.Pdf for .NET 6.6":
        return None

    logger.debug("Found a document generated by Aspose.Pdf, could be a Xero invoice.")

    text_boxes = document[1]
    if text_boxes[0] != "TAX INVOICE\n":
        return None

    invoice_date_box = text_boxes.find_box_starting_with("Invoice Date\n")
    if invoice_date_box is None:
        return None

    invoice_date = dateparser.parse(invoice_date_box.split("\n")[1], languages=["en"])
    if invoice_date is None:
        return None

    if not (
        invoice_number_box := text_boxes.find_box_starting_with("Invoice Number\n")
    ):
        return None
    invoice_number = invoice_number_box.split("\n")[1]

    logger.debug(
        "It states it is a tax invoice, and has an invoice date, assuming the expected format."
    )

    account_address = text_boxes[1]

    if text_boxes.index(invoice_date_box) != 2:
        possible_source_index = 2
    else:
        logger.debug("No source address on third box, looking after VAT Number.")
        vat_box_index = text_boxes.find_index_starting_with("VAT Number\n")

        if vat_box_index is None or text_boxes[vat_box_index + 1].startswith(
            "Description\n"
        ):
            logger.debug("Unable to find the source address, maybe wrong format.")
            return None

        possible_source_index = vat_box_index + 1

    source_address = text_boxes[possible_source_index]

    return NameComponents(
        invoice_date,
        extract_account_holder_from_address(source_address),
        extract_account_holder_from_address(account_address),
        "Invoice",
        document_number=invoice_number,
    )
